export default {
  initialColorMode: "red",
  colors: {
    text: "#fff",
    background: "#1c0000",
    headerText: "white",
    headerBG: "#8a0000",
    headerShadow: "0 16px 20px 0 rgba(0,0,0,0.2)",
    footerBG: "#630000",
    footerText: "#dedede",
    cardHeader: "white",
    cardBG: "#470000",
    cardText: "#dedede",
    cardLink: "white",
    cardShadow: "0 16px 20px 0 rgba(0,0,0,0.2)",
    heroBG: "#1f0000",
    heroText: "white",
    buttonBorder: "white",
    buttonBG: "#3d0000",
    buttonText: "white",
    avatarBG: "white",
    avatarText: "black",
    inputBorder: "white",
    inputText: "white",
    inputBG: "black",
    curtainText: "white",
    curtainBG: "#8a0000",
    hamburgerBG: "white",
    modes: {
      light: {
        text: "#000",
        background: 'white',
        headerText: "white",
        headerBG: '#1c0000',
        headerShadow: "0 16px 20px 0 rgba(0,0,0,0.2)",
        footerBG: "black",
        footerText: "#bdbdbd",
        cardHeader: "black",
        cardBG: "#ffffff",
        cardText: "black",
        cardLink: "black",
        cardShadow: "rgba(0,0,0,0.2)",
        heroBG: "white",
        heroText: "black",
        buttonBorder: "black",
        buttonBG: "#ffffff",
        buttonText: "black",
        avatarBG: "black",
        avatarText: "white",
        inputBorder: "black",
        inputText: "black",
        inputBG: "#f2f2f2",
        curtainText: "black",
        curtainBG: "white",
        hamburgerBG: "white",
      },
      dark: {
        text: 'white',
        background: '#121111', //"#0a0a0a",
        headerText: 'white',
        headerBG: '#0d0a09', // "#171717",
        headerShadow: "0 16px 20px 0 rgba(0,0,0,0.2)",
        footerBG: "#171717",
        footerText: "white",
        cardHeader: "white",
        cardBG: "#0d0a09",
        cardText: "white",
        cardLink: "white",
        cardShadow: "0 16px 20px 0 rgba(0,0,0,0.2)",
        heroBG: "black",
        heroText: "white",
        buttonBorder: "white",
        buttonBG: "#121212",
        buttonText: "white",
        avatarBG: "white",
        avatarText: "#fce1d7",
        inputBorder: "white",
        inputText: "white",
        inputBG: "black",
        curtainText: "#fce1d7",
        curtainBG: "black",
        hamburgerBG: "white",
      },
    },
  },
}
